SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `fmslog` (
  `id` int(11) NOT NULL,
  `c-client-id` varchar(100) DEFAULT NULL,
  `c-ip` varchar(15) DEFAULT NULL,
  `c-agent` varchar(100) NOT NULL,
  `c-ip-country` varchar(30) DEFAULT NULL,
  `x-file-name` varchar(60) DEFAULT NULL,
  `x-sname` varchar(40) DEFAULT NULL,
  `connect-timestamp` datetime DEFAULT NULL,
  `disconnect-timestamp` datetime DEFAULT NULL,
  `x-duration` int(11) DEFAULT NULL,
  `sc-bytes` int(11) DEFAULT NULL,
  `sc-stream-bytes` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


ALTER TABLE `fmslog`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `fmslog`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
